#
# Your Crowdin credentials
#
project_id : "8"
api_token : "CROWDIN_PERSONAL_TOKEN"
base_path : "."
base_url : "https://org-test.crowdin.com"

#
# Choose file structure in Crowdin
#
preserve_hierarchy : true

#
# Use YAML anchor to implement the global languages mapping
#
languages_mapping: &global_languages_mapping
  locale:
    ja:     ja_JP
    ru:     ru_RU
    zh-CN:  zh_CN
    zh-TW:  zh_TW

#
# Files configuration
#
files:
  - source: /locale/pot/**/*.pot
    translation: /.tmstmp/%locale%/**/%file_name%.po
    languages_mapping: *global_languages_mapping
