# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: ci-pr-merged-to-l10n

on:
  pull_request:
    branches:
      - l10n
    types:
      - closed

jobs:
  precondition:
    if: ${{ ( ( github.event_name == 'pull_request' ) &&
              ( github.event.pull_request.merged == 'true' ) &&
              ( contains(github.event.pull_request.labels.*.name, 'gettext') ||
                contains(github.event.pull_request.labels.*.name, 'crowdin') ) ) }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Secrets
        shell: bash
        run: |
          SECRETS_EXIST=true
          if [[ -z "${{ secrets.ACTOR_GITHUB_TOKEN }}" ]]; then
            echo "secrets.ACTOR_GITHUB_TOKEN is missing."
            SECRETS_EXIST=false
          fi
          if [[ "${SECRETS_EXIST}" == "false" ]]; then
            echo "Error: Some secrets are missing." >&2
            exit 1
          fi
      - name: Check Variables
        shell: bash
        run: |
          VARIABLES_EXIST=true
          if [[ "${VARIABLES_EXIST}" == "false" ]]; then
            echo "Error: Some variables are missing." >&2
            exit 1
          fi

  caller:
    needs: [ 'precondition' ]
    if: ${{ ( ( github.event_name == 'pull_request' ) &&
              ( github.event.pull_request.merged == 'true' ) &&
              ( contains(github.event.pull_request.labels.*.name, 'gettext') ||
                contains(github.event.pull_request.labels.*.name, 'crowdin') ) ) }}
    uses: hwhsu1231/ci-sphinx/.github/workflows/use-pr-merged-to-l10n.yml@main
    with:
      RUNNER: 'ubuntu-latest'
      PR_TITLE: ${{ github.event.pull_request.title }}
      GETTEXT: ${{ contains(github.event.pull_request.labels.*.name, 'gettext') }}
      TMSCLI: ${{ contains(github.event.pull_request.labels.*.name, 'tmscli') }}
      CALLER_JOB: 'caller'
      ENABLE_JOB: true
    secrets:
      ACTOR_GITHUB_TOKEN: ${{ secrets.ACTOR_GITHUB_TOKEN }}
