# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: ci-tmscli-push-pot

on:
  # Triggers the workflow when a pull request is merged to the 'l10n' branch.
  repository_dispatch:
    types:
      - pr-merged-to-l10n
  # Triggers the workflow manually through the GitHub UI.
  workflow_dispatch:
    inputs:
      TYPE:
        description: 'TYPE input'
        required: true
        type: choice
        default: 'matrix'
        options:
          - 'matrix'
          - 'single'
      VERSION:
        description: 'VERSION input (for single type)'
        required: true
        type: string
        default: 'git-master'
      VERSION_GROUP:
        description: 'VERSION_GROUP input (for matrix type)'
        required: true
        type: choice
        default: 'all'
        options:
          - 'all'
          - 'dev'
          - 'v3'

jobs:
  precondition:
    if: ${{ ( ( github.event_name == 'repository_dispatch' &&
                github.event.action == 'pr-merged-to-l10n' &&
                github.event.client_payload.TMSCLI == 'true' ) ||
              ( github.event_name == 'workflow_dispatch' && inputs.TYPE == 'matrix' ) ||
              ( github.event_name == 'workflow_dispatch' && inputs.TYPE == 'single' ) ) }}
    runs-on: ubuntu-latest
    steps:
      - name: Print Contexts/Inputs
        shell: bash
        run: |
          echo "[Contexts]"
          echo "github.job = ${{ github.job }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.ref_name = ${{ github.ref_name }}"
          echo "github.event_name = ${{ github.event_name }}"
          echo "github.event.client_payload.TYPE = ${{ github.event.client_payload.TYPE }}"
          echo "github.event.client_payload.VERSION = ${{ github.event.client_payload.VERSION }}"
          echo "github.event.client_payload.LANGUAGE = ${{ github.event.client_payload.LANGUAGE }}"
          echo "github.event.client_payload.GETTEXT = ${{ github.event.client_payload.GETTEXT }}"
          echo "github.event.client_payload.TMSCLI = ${{ github.event.client_payload.TMSCLI }}"
          echo "[Inputs]"
          echo "inputs.TYPE = ${{ inputs.TYPE }}"
          echo "inputs.VERSION = ${{ inputs.VERSION }}"
          echo "inputs.VERSION_GROUP = ${{ inputs.VERSION_GROUP }}"
          echo "[Variables]"
          echo "vars.ACTOR_ID = ${{ vars.ACTOR_ID }}"
          echo "vars.ACTOR_NAME = ${{ vars.ACTOR_NAME }}"
          echo "vars.ACTOR_LOGIN = ${{ vars.ACTOR_LOGIN }}"
          echo "[Secrets]"
          echo "secrets.CROWDIN_PERSONAL_TOKEN = ${{ secrets.CROWDIN_PERSONAL_TOKEN }}"
      - name: Check Variables
        shell: bash
        run: |
          VARIABLES_EXIST=true
          if [[ -z "${{ vars.ACTOR_ID }}" ]]; then
            echo "vars.ACTOR_ID is missing."
            VARIABLES_EXIST=false
          fi
          if [[ -z "${{ vars.ACTOR_NAME }}" ]]; then
            echo "vars.ACTOR_NAME is missing."
            VARIABLES_EXIST=false
          fi
          if [[ -z "${{ vars.ACTOR_LOGIN }}" ]]; then
            echo "vars.ACTOR_LOGIN is missing."
            VARIABLES_EXIST=false
          fi
          if [[ "${VARIABLES_EXIST}" == "false" ]]; then
            echo "Error: Some variables are missing." >&2
            exit 1
          fi
      - name: Check Secrets
        shell: bash
        run: |
          SECRETS_EXIST=true
          if [[ -z "${{ secrets.CROWDIN_PERSONAL_TOKEN }}" ]]; then
            echo "secrets.CROWDIN_PERSONAL_TOKEN is missing."
            SECRETS_EXIST=false
          fi
          if [[ "${SECRETS_EXIST}" == "false" ]]; then
            echo "Error: Some secrets are missing." >&2
            exit 1
          fi

  get-matrix:
    needs: [ 'precondition' ]
    if: ${{ ( ( github.event_name == 'repository_dispatch' &&
                github.event.action == 'pr-merged-to-l10n' &&
                github.event.client_payload.TMSCLI == 'true' ) ||
              ( github.event_name == 'workflow_dispatch' && inputs.TYPE == 'matrix' ) ||
              ( github.event_name == 'workflow_dispatch' && inputs.TYPE == 'single' ) ) }}
    runs-on: ubuntu-latest
    outputs:
      VERSION_NUM: ${{ steps.gvlv.outputs.VERSION_NUM }}
      VERSION_LIST: ${{ steps.gvlv.outputs.VERSION_LIST }}
    steps:
      - name: Checkout to '${{ github.ref }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Get the Version List from versions.json
        id: gvlv
        uses: hwhsu1231/ci-sphinx/.github/actions/get-version-list-from-versions-file@main
        with:
          type: ${{ inputs.TYPE || github.event.client_payload.TYPE }}
          version: ${{ inputs.VERSION || github.event.client_payload.VERSION }}
          version-group: ${{ inputs.VERSION_GROUP }}
          version-filter: 'tmscli'

  caller:
    needs: [ 'get-matrix' ]
    if: ${{ ( ( github.event_name == 'repository_dispatch' &&
                github.event.action == 'pr-merged-to-l10n' &&
                github.event.client_payload.TMSCLI == 'true' ) ||
              ( github.event_name == 'workflow_dispatch' && inputs.TYPE == 'matrix' ) ||
              ( github.event_name == 'workflow_dispatch' && inputs.TYPE == 'single' ) ) &&
            ( needs.get-matrix.outputs.VERSION_NUM != '0' ) }}
    strategy:
      matrix:
        VERSION: ${{ fromJSON(needs.get-matrix.outputs.VERSION_LIST) }}
      fail-fast: false
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.VERSION }}
      cancel-in-progress: true
    uses: hwhsu1231/ci-sphinx/.github/workflows/use-tmscli-push-pot.yml@main
    with:
      RUNNER: 'ubuntu-latest'
      CHECKOUT: ${{ github.ref }}
      VERSION: ${{ matrix.VERSION }}
      ENABLE_JOB: true
      ACTOR_ID: ${{ vars.ACTOR_ID }}
      ACTOR_NAME: ${{ vars.ACTOR_NAME }}
      ACTOR_LOGIN: ${{ vars.ACTOR_LOGIN }}
    secrets:
      CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
