# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: test4

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'VERSION input (for single type)'
        required: true
        type: string
        default: 'git-master'
      VERSION_GROUP:
        description: 'VERSION_GROUP input (for matrix type)'
        required: true
        type: choice
        default: 'v3'
        options:
          - 'all'
          - 'dev'
          - 'v3'

env:
  CRON_dev: '0 8 * * 1'
  CRON_v3:  '0 8 1 * *'
  CRON_v4:  '0 8 2 * *'
  CRON_v5:  '0 8 3 * *'

jobs:
  single:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'windows-latest'
          - 'macos-latest'
          - 'ubuntu-latest'
      fail-fast: false
    steps:
      - name: Checkout to '${{ github.ref }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Get VERSION_GROUP from Inputs or Schedule
        id: gvg
        shell: bash
        run: |
          # 動態抓取所有 CRON_* 環境變數
          for CRON_VAR in $(env | grep '^CRON_' | cut -d'=' -f1); do
            # echo "${CRON_VAR} : ${!CRON_VAR}"
            GROUP_NAME="${CRON_VAR/CRON_/}"
            GROUP_CRON="${!CRON_VAR}"
            echo "${GROUP_NAME} : ${GROUP_CRON}"
            if [[ "${GITHUB_EVENT_SCHEDULE}" == "${!CRON_VAR}" ]]; then
              VERSION_GROUP="${CRON_VAR/CRON_/}"
              break
            fi
          done

          # # 輸出 VERSION_GROUP 結果
          # echo "VERSION_GROUP:"
          # echo "${VERSION_GROUP}"
