# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: test-caller

on:
  # Triggers the workflow manually through the GitHub UI.
  workflow_dispatch:
    inputs:
      CALLER_BOOLEAN_TRUE_INPUT:
        description: xxx
        type: boolean
        default: true
      CALLER_BOOLEAN_FALSE_INPUT:
        description: xxx
        type: boolean
        default: false
      CALLER_STRING_TRUE_INPUT:
        description: xxx
        type: string
        default: 'true'
      CALLER_STRING_FALSE_INPUT:
        description: xxx
        type: string
        default: 'false'

jobs:
  caller:
    uses: ./.github/workflows/test-callee.yml
    with:
      BOOLEAN_INPUT1: true
      BOOLEAN_INPUT2: false
      BOOLEAN_INPUT3: ${{ inputs.CALLER_BOOLEAN_TRUE_INPUT }}
      BOOLEAN_INPUT4: ${{ inputs.CALLER_BOOLEAN_FALSE_INPUT }}
      STRING_INPUT1: 'true'
      STRING_INPUT2: 'false'
      STRING_INPUT3: ${{ inputs.CALLER_BOOLEAN_TRUE_INPUT }}
      STRING_INPUT4: ${{ inputs.CALLER_BOOLEAN_FALSE_INPUT }}
      STRING_INPUT5: ${{ inputs.CALLER_STRING_TRUE_INPUT }}
      STRING_INPUT6: ${{ inputs.CALLER_STRING_FALSE_INPUT }}
