# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: test-caller

on:
  # Triggers the workflow manually through the GitHub UI.
  workflow_dispatch:
    inputs:
      CALLER_INPUT:
        description: xxx
        type: choice
        default: 'true'
        options:
          - 'true'
          - 'false'

jobs:
  caller:
    uses: ./.github/workflows/test-callee.yml
    with:
      STRING_INPUT1: 'true'
      STRING_INPUT2: 'false'
      BOOLEAN_INPUT1: true
      BOOLEAN_INPUT2: false
      BOOLEAN_INPUT3: ${{ inputs.CALLER_INPUT }}
