# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: test-callee

on:
  workflow_call:
    inputs:
      BOOLEAN_INPUT1:
        required: true
        type: boolean
      BOOLEAN_INPUT2:
        required: true
        type: boolean
      BOOLEAN_INPUT3:
        required: true
        type: boolean
      BOOLEAN_INPUT4:
        required: true
        type: boolean

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Print Inputs
        shell: bash
        run: |
          echo "[Test]"
          echo "inputs.BOOLEAN_INPUT1             : ${{ inputs.BOOLEAN_INPUT1 }}"
          echo "inputs.BOOLEAN_INPUT2             : ${{ inputs.BOOLEAN_INPUT2 }}"
          echo "inputs.BOOLEAN_INPUT3             : ${{ inputs.BOOLEAN_INPUT3 }}"
          echo "inputs.BOOLEAN_INPUT4             : ${{ inputs.BOOLEAN_INPUT4 }}"
          echo "!inputs.BOOLEAN_INPUT1            : ${{ !inputs.BOOLEAN_INPUT1 }}"
          echo "!inputs.BOOLEAN_INPUT2            : ${{ !inputs.BOOLEAN_INPUT2 }}"
          echo "!inputs.BOOLEAN_INPUT3            : ${{ !inputs.BOOLEAN_INPUT3 }}"
          echo "!inputs.BOOLEAN_INPUT4            : ${{ !inputs.BOOLEAN_INPUT4 }}"
          echo "toJSON(inputs.BOOLEAN_INPUT1)     : ${{ toJSON(inputs.BOOLEAN_INPUT1) }}"
          echo "toJSON(inputs.BOOLEAN_INPUT2)     : ${{ toJSON(inputs.BOOLEAN_INPUT2) }}"
          echo "toJSON(inputs.BOOLEAN_INPUT3)     : ${{ toJSON(inputs.BOOLEAN_INPUT3) }}"
          echo "toJSON(inputs.BOOLEAN_INPUT4)     : ${{ toJSON(inputs.BOOLEAN_INPUT4) }}"
          echo "inputs.BOOLEAN_INPUT1 == 'true'   : ${{ inputs.BOOLEAN_INPUT1 == 'true' }}"
          echo "inputs.BOOLEAN_INPUT2 == 'true'   : ${{ inputs.BOOLEAN_INPUT2 == 'true' }}"
          echo "inputs.BOOLEAN_INPUT3 == 'true'   : ${{ inputs.BOOLEAN_INPUT3 == 'true' }}"
          echo "inputs.BOOLEAN_INPUT4 == 'true'   : ${{ inputs.BOOLEAN_INPUT4 == 'true' }}"
          echo "inputs.BOOLEAN_INPUT1 == 'false'  : ${{ inputs.BOOLEAN_INPUT1 == 'false' }}"
          echo "inputs.BOOLEAN_INPUT2 == 'false'  : ${{ inputs.BOOLEAN_INPUT2 == 'false' }}"
          echo "inputs.BOOLEAN_INPUT3 == 'false'  : ${{ inputs.BOOLEAN_INPUT3 == 'false' }}"
          echo "inputs.BOOLEAN_INPUT4 == 'false'  : ${{ inputs.BOOLEAN_INPUT4 == 'false' }}"
